### PR TITLE
Map Area Fixes - Issue 34

### LINKED ISSUE #34: Numbers in input field can linger without being assigned
Changes in ther "Areas" tab do not show changes or just dismiss all changes when you clicke another tab or setting.

### PR DESCRIPTION
**Pull request by kent-sole**
**Closes #34**
- Added QoL prototype tabbing in AreaListObject
- Added Deselect logic to ALO
- Partially cleaned up AreaInfo class
- Updated logic in AreaInfo to function as requested

**TODO**
- Propagate this fix to the other Input Field prefabs

### CODE REVIEW

File: Assets/Scripts/UI/Lists/AreaListObject.cs [hunk 1]
```diff
@@ -28,10 +28,56 @@ public void OnToggle()
...
 	}
 
 	public void OnRemove()
 	{
 		Controler.Remove(InstanceId);
 	}
+
+	// TODO: We need a top-level input monitor that raises events the rest of the UI can listen for like "MoveToNextField".
+	// Consider this code a QoL Prototype. We'll put something like this on each of the Vector/Color fields. Or we could do
+	// something more comprehensive - but that would mean paying closer attention to EVERY interactable element in the entire UI
```
Comment (BlackYps) [inline Assets/Scripts/UI/Lists/AreaListObject.cs:44]: please limit the line length of comments to something reasonable. E.g. 80 characters

File: Assets/Scripts/UI/Tools/Map/AreaInfo.cs [hunk 2]
```diff
@@ -16,24 +15,35 @@ public class AreaInfo : MonoBehaviour {
...
+		}
 	}
+	
 
 	private void Awake()
 	{
 		Current = this;
+		
+		// These controls are currently not being used. I am disabling them like this instead of in the Editor to make 
+		// it clear in the code that we aren't using them. If we continue to not use them, we should remove them entirely.
```
Comment (BlackYps) [inline Assets/Scripts/UI/Tools/Map/AreaInfo.cs:38]: I'm not a fan of leaving things in an intermediary state if there are not good reasons for it.
Experience shows that these things will never be addressed again. We should remove them entirely and when there is new functionality that needs a new button it will not be hard to add one again.

**Review by BlackYps — CHANGES_REQUESTED** [review]
I also noticed that I can erase the number from the input field and it will stay empty, which looks bad. It should default to 0, or whatever it is internally using as default.

File: Assets/Scripts/UI/Lists/AreaListObject.cs (hunk 1 above)
Comment (kent-sole) [reply Assets/Scripts/UI/Lists/AreaListObject.cs]: Comment reduced

File: Assets/Scripts/UI/Tools/Map/AreaInfo.cs (hunk 2 above)
Comment (kent-sole) [reply Assets/Scripts/UI/Tools/Map/AreaInfo.cs]: Hidden elements removed, code adjusted

**Comment by kent-sole** [comment]
> I also noticed that I can erase the number from the input field and it will stay empty, which looks bad. It should default to 0, or whatever it is internally using as default.

I added a utility to do this. It will have to be applied to every input field prefab manually as this is not a default function of the Unity InputField. We can do this when we propagate the other fixes to the input fields.

File: Assets/Scripts/UI/Utils/InputDefaultValueOnEnd.cs [hunk 3]
```diff
@@ -0,0 +1,21 @@
+using UnityEngine;
+using UnityEngine.UI;
+
+[RequireComponent(typeof(InputField))]
+public class InputDefaultValueOnEnd : MonoBehaviour
```
Comment (BlackYps) [inline Assets/Scripts/UI/Utils/InputDefaultValueOnEnd.cs:5]: How is this actually used?

File: Assets/Scripts/UI/Tools/Map/AreaInfo.cs [hunk 4]
```diff
@@ -85,99 +85,142 @@ void Generate()
...
+		}
+		SelectedArea = null;
+		MapLuaParser.Current.UpdateArea(Rounding.isOn);
+	}
+	
+	private void SetSelectionToDefault()
+	{
+		HideArea = false;
+		DeselectAll();
+	}
```
Comment (BlackYps) [inline Assets/Scripts/UI/Tools/Map/AreaInfo.cs:169]: Is this still needed?

**Review by BlackYps — COMMENTED** [review]
A general note: Please only force push if you need to rebase the branch onto latest changes of master. I don't expect this to happen in this repo, because you and I are basically the only ones doing changes at the moment. When you add new changes after a review please add a new commit instead. It makes it easier to review your changes.

I tested the functionality and in general it seems to work well, but if you load a map that already has an area defined it will only show up in the ui after I added a new area with the button. Then I see both the old and new area. Tested on Optima Ferox.

File: Assets/Scripts/UI/Utils/InputDefaultValueOnEnd.cs (hunk 3 above)
Comment (kent-sole) [reply Assets/Scripts/UI/Utils/InputDefaultValueOnEnd.cs:5]: This component is added to any object with an input field. The "RequireComponent" tag will enforce this requirement. It functions automatically. Whatever you enter (in the editor) for the "DefaultValue" is automatically injected into the input field if the user deselects the input field and leaves it empty.

File: Assets/Scripts/UI/Tools/Map/AreaInfo.cs (hunk 4 above)
Comment (kent-sole) [reply Assets/Scripts/UI/Tools/Map/AreaInfo.cs:169]: Doesn't look like it

**Review by BlackYps — APPROVED** [review]
Works perfectly now!
